language: node_js
node_js: v6
sudo: false
addons:
  ssh_known_hosts: ssh-oncletom.alwaysdata.net

before_install:
- npm config set production false

before_deploy:
- openssl aes-256-cbc -K $encrypted_a47c168ad38c_key -iv $encrypted_a47c168ad38c_iv -in id_rsa.enc -out /tmp/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa
- ssh-add /tmp/id_rsa

env:
  matrix:
  - NODE_ENV=production
  global:
    secure: "c5gAW/tPNCNh5DgfYU/WMErx3OFVcEt/BeIWJZRf08M02IKtnPQqxxoCm5PF8mFxdWrIPnZPN0GO6yhKWTsxKZYkPelKareROu3KaRmAzMEoZLYipZ95O6kd1eR98N4iE5BylLMM1trGzUfCuSBDmBWNXjf5TwQJ+ewmDV4iEjQ="

deploy:
- provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: npm run index-content
  skip_cleanup: true
  on:
    branch: master
