# Hexo Configuration
## Docs: http://zespia.tw/hexo/docs/configure.html
## Source: https://github.com/tommy351/hexo/

# Site
title: oncletom.io
subtitle: A blog about *Web technologies* and *human experience*.
description: "Hey, I'm Thomas! A french web engineer living in London and working for BBC R&D. I express my views and interests about Web development, Node.js, Docker and long-term life experiences."
author: Thomas Parisot
email: hi@oncletom.io
default_cover: https://oncletom.io/images/thomas-parisot.jpg
external_link: true
language: fr
keywords:
  - javascript
  - docker
  - node.js
  - html5
  - web
  - frontend
  - development
  - entreprise
  - france
  - united kingdom
  - london

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://oncletom.io
root: /
permalink: :year/:title/
tag_dir: tags
archive_dir: ""
category_dir: categories
code_dir: downloads/code

# Writing
new_post_name: :year/:title.md # File name of new posts
default_layout: post
auto_spacing: false # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
max_open_file: 100
filename_case: 1
highlight:
  auto_detect: false
  enable: true
  line_number: true
  tab_replace: 2

# Category & Tag
default_category: uncategorized
category_map:
  JavaScript: javascript
  WebDev: web
  Events: events
  Projects: projects
  Personal Views: meta
  Work & Labour: work
  WordPress: wordpress
  a11y: a11y
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 0

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
logger: false
logger_format:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: dddd Do MMMM YYYY
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Disqus
disqus_shortname: oncletom

# Extensions
## Plugins: https://github.com/tommy351/hexo/wiki/Plugins
## Themes: https://github.com/tommy351/hexo/wiki/Themes
theme: ../node_modules/hexo-theme-oncletom
layout: blog

graph:
  google_plus:    ~
  facebook:       ~
  twitter:        oncletom

# Content Indexing
## See https://www.npmjs.com/package/hexo-algolia
algolia:
  applicationID: 'QIP7Z1PL3B'
  apiKey: '5caf0f682ba8349e8a67872b9edde3f3'
  indexName: 'prod_blog'
  chunkSize: 5000

# Deployment
## Docs: http://zespia.tw/hexo/docs/deploy.html
deploy:
  type: rsync
  host: ssh-oncletom.alwaysdata.net
  user: oncletom
  root: ~/
  delete: false
  exclude: [.ssh, .bash*, .htaccess, talks, node_modules, bower_components]
