menu:
  Expertise Web: http://cyneticmonkey.com
  Blog: /
  Conférences: http://cyneticmonkey.com/talks

links:
  RSS: /feed/
  Twitter: https://twitter.com/oncletom
  Code: https://github.com/oncletom
  Photos: http://flickr.com/photos/the-jedi/